### ISSUE TITLE
[W6-api-sentiment-project] Xabier Arrieta

### ISSUE THREAD

**Issue by XabierArrieta** [Ironhack-Data-Madrid-Enero-2021/W6-api-sentiment-project#1]
https://github.com/XabierArrieta/api-sentiment-project

**Comment by XabierArrieta** [comment]
este no es el proyecto final, lo he tenido que volver a subir, y está en otro repositorio.
https://github.com/XabierArrieta/Project-API

**Comment by olmocorell** [comment]
¡¡Hola Hola Xabiiiiiiiiiii!!  🚀 👓 💪🏻 
En primerito lugar.... ¡¡qué fantasía ver que tu proyecto es de Harry Potter!!


### Readme
Está perfecto, si acaso yo habría puesto algún ejemplo de código de cómo usar los endpoints tipo documentación:
![Captura de pantalla 2021-02-24 a las 10 05 06](https://user-images.githubusercontent.com/57899051/108976416-c6a07880-7687-11eb-92aa-6d1851601141.png)
Viendo esto, seguro que se puede mejorar, pero así es como lo puse yo en el readme, un ejemplo de cómo había que tener los datos estructurados para hacer las request a la API.

### Code/Repository structure
La estructura del repo se puede modificar y mejorar un poco, entiendo que meter las cosas en carpetas es tedioso a la hora de tener errores con los import, porque sé que dan fallo y que hay que meter archivos __init__ o append path para que funcione bien y no dé problemas.
De cara al futuro, mi consejo es:
Hazte una rama de este repositorio (si no sabes lo que es lo hablamos....) y ahí vas haciendo las pruebas, empiezas a modularizar y a colocar cosas en sitios. Mientras tanto, tu rama master seguirá intacta, tendrás una copia de tu código funcionando por si lo rompes en la rama 😄. 

### Code efficiency / Code syntax (conventions)
[Aquí](https://github.com/XabierArrieta/Project-API/blob/master/Api%20test.ipynb) en este jupyter. Te cuento que solamente había que importar el módulo request. 
¿Por qué? Porque si tenemos nuestra api corriendo en local, no necesitamos importar nada más, la api hace todas las conexiones con mongo y es ella la que, precisamente, es la intermediaria entre mongo y tu jupyter. Ese es el objetivo principal de la API, hacer de intermediaria entre un cliente y una base de datos. En este caso, corriendo todo en local, el cliente es el jupyter notebook, la api es el servidor y es la que conecta con la base de datos y hace las operaciones necesarias para devolver los datos al cliente que solamente necesita hacer una llamada a un endpoint con los parámetros que se consideren.

El sentiment análisis está guay, y te lo has currado un montón con las grafiquitas y todo!! Habría estado muy guay lo que dije, que intentaras meter el sentiment en un endpoint .

La estructura del código y la modularización de la API están bien.
Como idea para modularizar aún más, un archivo de funciones check, y sacar estos if de los endpoint.
![Captura de pantalla 2021-02-24 a las 10 41 06](https://user-images.githubusercontent.com/57899051/108981211-ce165080-768c-11eb-9da0-9215b6a5a8fc.png)

Por lo demás está genial Xabi, ¡¡has hecho muy buen trabajo!!

### Improvements

- Ejemplo de código en el readme
- Un poco más de atomización / funciones check
- Jupyter echar un ojo
- Mejoras de cara a futuro para implementar.

¡¡Muy buen trabajo!! Enhorabuena Xabi, tu proyecto está genial.

![unnamed](https://user-images.githubusercontent.com/57899051/108981591-28afac80-768d-11eb-86f0-eaa2d7fb5149.png)
