### ISSUE TITLE
 [W6-api-sentiment-project] Mario García

### ISSUE THREAD

**Issue by MarioGar25** [Ironhack-Data-Madrid-Enero-2021/W6-api-sentiment-project#10]
Mi repo : https://github.com/MarioGar25/Sentiment-project

**Comment by olmocorell** [comment]
¡¡Hola Hola Marioooooooo!! 🚀 💪🏻 🚀 💪🏻 
En primer lugar te pido disculpas por haber tardado tanto en venir a corregir este proyecto.
Por otra parte.... Harry Potteeeeeeeeeeeeeeeeeeeeeeer!!! ♥️ 

### Readme
En cuanto al readme, te cuento:
¿Qué te falta?
- Stack de tecnologías con enlaces tipo así
![Captura de pantalla 2021-03-03 a las 7 46 16](https://user-images.githubusercontent.com/57899051/109764997-89db0100-7bf4-11eb-8dac-370270ac2d75.png)
- Ejemplos de llamadas a la api
Algún ejemplo de código de cómo usar los endpoints tipo documentación:
<img width="873" alt="Captura de pantalla 2021-02-26 a las 10 27 35" src="https://user-images.githubusercontent.com/57899051/109281981-3f850900-781d-11eb-9859-2a48314741eb.png">
Viendo esto, seguro que se puede mejorar, pero así es como lo puse yo en el readme, un ejemplo de cómo había que tener los datos estructurados para hacer las request a la API.

### Code/Repository structure
Aquí:
![Captura de pantalla 2021-03-09 a las 18 27 49](https://user-images.githubusercontent.com/57899051/110512057-29245a80-8105-11eb-83df-592ef298efb5.png)
Me falta un opco de organización.
Habría metido los notebooks en una carpeta de notebooks y si acaso habría dejado fuera con el que haces todas las pruebas para que veamos cómo funciona tu api y lo dejas ejecutado para que veamos que funciona.

### Code efficiency / Code syntax (conventions)
[Esto](https://github.com/MarioGar25/Sentiment-project/blob/main/API_Test.ipynb) está ¡¡PERFECTO!!.
Además haces un endpoint con el sentiment analysis ... ¡¡SÚPER TOP!! 🏅 ¡¡enhorabuena!!

Está perfecto que hagas los endpoints con funciones pequeñitas parametrizadas.
![Captura de pantalla 2021-03-09 a las 18 32 25](https://user-images.githubusercontent.com/57899051/110512779-ce3f3300-8105-11eb-9f4f-29f8b143788b.png)

En general, tu código está impecable, muy limpio, organizado y todo con docstrings. Has hecho un proyecto de 10, Mario.
Algunas funciones sin documentar por [aquí](https://github.com/MarioGar25/Sentiment-project/blob/main/helper_utils/endpoints.py) ... pero en general, muy buen trabajo.

Genial el mongo conection explicado y súper bien las funciones de check parametrizadas.

¡¡¡Muy buen trabajo!!!! Está excelente.
¡¡Enhorabuena!!


![unnamed](https://user-images.githubusercontent.com/57899051/110513047-12cace80-8106-11eb-9844-bddb07546d1c.png)
