### ISSUE TITLE
[W6-api-sentiment-project] Jean Charles Yamada 

### ISSUE THREAD

**Issue by yamadajc** [Ironhack-Data-Madrid-Enero-2021/W6-api-sentiment-project#11]
https://github.com/yamadajc/api-sentiment-project

**Comment by breogann** [comment]
Hola Jeancha! 🙋🏻‍♂️

Te coy contando:

- Respecto a la **organización del repositorio 📚**
    - El .gitignore: ¿no tienes? no se te ha colado ningún archivo oculto/temporal, pero pondría un .gitignore por si acaso.
    - Por lo demás, la organización de carpetas y de de archivos en la root está perfect! quizá pondría la [api.py](http://api.py) (y también la carpeta de helpers) a nivel de la root. Los archivos que ejecutan las aplicaciones tienen que estar visibles según abres el repo. Para alguien que se lo clone, es el primer archivo que buscará.
- El **[README.md](http://readme.md) ✍🏻**:
    - Súuper bien explicado. Has incluido las tecnologías, enlaces, etc.
    - También has puesto ejemplos de los endpoints
    - Y gráficas con el resultado 👏
    - Nada que decir, como siempre, que alguien que no sepa de código sea capaz de entender lo que habéis hecho.
- El **código 👩‍💻:**
    - En general: No has hecho los docstrings. Fíjate cuántas funciones tienes y todas repartidas. Acostúmbrate a poner docstring diciendo qué hace cada función y qué recibe y qué devuelve; sobre todo por hacerte un favor a tu yo del futuro. Añade también comentarios en hashtags si crees que pueden añadir valor.
    - También súper buena modularización de las funciones 👏
    - En `api.py`
        - Has definido:

            ```python
            app = Flask("ApiSiente")
            ```

            cuando definimos la app de Flask, lo hacemos con "__name__". Lo que hace es llamarse a sí mismo; es algo interno de python, no es un "format" como tal. Te dejo este artículo que lo explica: [https://blog.miguelgrinberg.com/post/why-do-we-pass-name-to-the-flask-class](https://blog.miguelgrinberg.com/post/why-do-we-pass-name-to-the-flask-class)

        - Por lo demás en este archivo está todo bien: código sintético donde llamas a otras funciones que hacen otras cosas. Aquí sólo los decoradores y las funciones básicas que llaman a otras.
    - En `endpoints`
        - Has puesto:

            ```python
            def list_all(typ):
                settings = setup(typ)
                res = read_coll(typ,{})
                return res
            ```

            ¿qué hace settings? guardas la función de arriba en una variable pero luego no la utilizas. Entiendo que lo querías utilizar luego en el json de status, ¿no?

        - Como nos decías, puedes incluir el sentiment analysis dentro de un endpoint. Es cuestión de modularizar las funciones y poner un decorador más. Puedes incluso hacer que, en función de lo que pidas, devuelvas una gráfica. También puedes hacerlo por grupos, por usuarios, por usuarios en el tiempo (antes o después de un evento), por palabras más usadas, etc.
        - ¿Los tweets cómo los metiste? ¿a mano? si quieres seguir trabajando con twitter, ya sabes, ve pidiendo el token que tarda. La pregunta es por curiosidad, que ya sabes que para este proyecto lo importante no es la cantidad sino la estructura.

        Enhorabuena Jeancha! Has creado una base de datos, has creado enpdpoints de post, de get y has hecho un sentiment analysis.  A este proyecto siempre se le pueden añadir más cosas:  hacer más visualización, meter más datos, puedes deployearlo (para eso necesitas pasar la base de datos de Mongo Compass a Mongo Atlas), pero el proyecto está genial. En unas semanas habéis conseguido nutrir una base de datos a través d una aplicación vuestra y habeís sacado insights. Y esto es sólo el principio, esto lo puedes escalar de muchas formas. A tope Jeancha!! 💪 🚀

    ![image](https://user-images.githubusercontent.com/54676992/108981112-b0e18200-768c-11eb-9525-e1166f10739b.png)
