### ISSUE TITLE
[W6-api-sentiment-project] Sonia Garcia Fominaya

### ISSUE THREAD

**Issue by Fominayasg** [Ironhack-Data-Madrid-Enero-2021/W6-api-sentiment-project#12]

**Comment by Fominayasg** [comment]
https://github.com/Fominayasg/api-sentiment-project

**Comment by breogann** [comment]
Hola Sonia! 🙋🏻‍♂️

Te coy contando:

- Respecto a la **organización del repositorio 📚**
    - El .gitignore: No se te ha colado ningún archivo oculto/temporal, o sea que perfecto.
    - Por lo demás, la organización está perfecta. Quizá pondría [mongoConnection.py](http://mongoconnection.py) en una carpeta de **src**.
    - El archivo principal está bien en la root.
- El **[README.md](http://readme.md/) ✍🏻**:
    - Súuper bien explicado. Has incluido las tecnologías, enlaces, etc.
    - También has incluido ejemplos de los endpoints.
    - Puedes poner también alguna gráfica cuando hagas el sentiment analysis.
    - El sentiment analysis, cuando lo hagas, acuérdate de meterlo bajo un endpoint!
- El **código 👩‍💻:**
    - Has definido:

        ```python
        app = Flask("LIDLT")
        ```

        cuando definimos la app de Flask, lo hacemos con "__name__". Lo que hace es llamarse a sí mismo; es algo interno de python, no es un "format" como tal. Te dejo este artículo que lo explica: [https://blog.miguelgrinberg.com/post/why-do-we-pass-name-to-the-flask-class](https://blog.miguelgrinberg.com/post/why-do-we-pass-name-to-the-flask-class)

    - En general: No has hecho los docstrings. Acostúmbrate a poner docstring diciendo qué hace cada función y qué recibe y qué devuelve; sobre todo por hacerte un favor a tu yo del futuro. Aquí la manita no tiene que ir relajá.
    - También súper buena modularización de las funciones: en [api](http://apiu.py).py las funciones mínimas con los decoradores que llamen a funciones definidas en otros sitios, como helpers 👏
    - Respecto a la parametrización:

        ```python
        @app.route("/mensajes")
        def mensajes(): 
            data = read_data({},"Frases", project = {"_id":0,"Mensaje":1})
            return json_util.dumps(data)

        @app.route("/participantes")
        def participantes(): 
            data = read_data({},"Participantes", project = {"_id":0,"Nombre":1})
            return json_util.dumps(data)
        ```

        si las dos funciones lo que hacen es comprobar/traer cosas y depende de la colección de dónde vienen, puedes parametrizar la función para que en función de argumento haga una cosa o haga otra. Al final tener funciones muy parecidas puede ser señal de que hace falta refactorizar.

    - Otra cosa que puedes hacer además del try/except es crear funciones sencillas que comprueben y que las importes y llames dentro de otras.
    - Como decíamos ayer, puedes incluir el sentiment analysis dentro de un endpoint. Es cuestión de modularizar las funciones y poner un decorador más. Puedes incluso hacer que, en función de lo que pidas, devuelvas una gráfica. También puedes hacerlo por grupos, por usuarios, por usuarios en el tiempo (antes o después de un evento), por palabras más usadas, etc.
    - Para el jupyter, como decíamos ayer a Ana, sólo hace falta que importes requests. Al final el jupyter lo único que va a hacer es colocar la dirección en la barra de navegación de igual forma que lo harías tú. Y esa dirección lo que hace es llamar a la función del [api.py](http://api.py) que tiene debajo, que a su vez llama a la de mongo connection etc. Pero ese jupyter no hace conexión con la base de datos, sino que llama a la primera función que desencadena el resto.

    Enhorabuena Sonia! Has creado una base de datos, has creado enpdpoints de post, de get y no te queda casi nada para hacer sentiment analysis. A este proyecto siempre se le pueden añadir más cosas:  hacer más visualización, meter más datos, puedes deployearlo (para eso necesitas pasar la base de datos de Mongo Compass a Mongo Atlas), pero el proyecto está genial. En unas semanas habéis conseguido nutrir una base de datos a través de una aplicación vuestra y habéis sacado insights. Y esto es sólo el principio, esto lo puedes escalar de muchas formas. 

    A tope Sonia!! 💪 🚀

    ![https://user-images.githubusercontent.com/54676992/108981112-b0e18200-768c-11eb-9525-e1166f10739b.png](https://user-images.githubusercontent.com/54676992/108981112-b0e18200-768c-11eb-9525-e1166f10739b.png)
