### ISSUE TITLE
[W6-api-sentiment-project] Ana G

### ISSUE THREAD

**Issue by AnaAGG** [Ironhack-Data-Madrid-Enero-2021/W6-api-sentiment-project#13]
https://github.com/AnaAGG/P4_Api-sentiment-project.git

**Comment by breogann** [comment]
Hola Ana! 🙋🏻‍♂️

Te coy contando:

- Respecto a la **organización del repositorio 📚**
    - El .gitignore: perfecto, no se te ha colado ningún archivo temporal/oculto.
    - Por lo demás, lo único que te diría es que el archivo ejecutable principal iría en la root del repositorio. Al final cuando alguien se clona tu repositorio o se descarga un programa, lo primero que hará será buscar el archivo ejecutable: main.py, setup.py, app.py, etc. Al moverlo tendría que tener cuidado con las importaciones, eso sí.
    - Y esto ya es mi TOC, pero a la carpeta de QuoteAPI la llamaría **src.**
- El **[README.md](http://readme.md) ✍🏻**:
    - Súuper bien explicado. Has incluido las tecnologías, enlaces, etc.
    - También has puesto ejemplos de los endpoints y ejemplos de cómo sería el código con python 🤩
    - Y gráficas con el resultado 👏
    - Nada que decir, como siempre, que alguien que no sepa de código sea capaz de entender lo que habéis hecho.
    - Está muuuy bien el readme Ana!
- El **código 👩‍💻:**
    - Jupyters con las tablas de contenido 👏
    - Respecto a la parametrización:

        ```python
        @app.route("/Data") #to obtain all the information about authors, categories and phrases from our entire database
        def data():
            read = complete_list()
            return jsonify(read)

        @app.route("/AuthorId") #to obtain all the authors of the API
        def data_aut():
            read = complete_auth()
            return json_util.dumps(read)
        ```

        entiendo que las has separado porque la proyección es diferente, pero quizá podrías parametrizarla para que te reciba un argumento (tipo de colección)? También, la función de de def data_aut y la de complete_auth que utilizas dentro de ella, ¿no hacen prácticamente lo mismo?

    - Súuper bien los docstrings
    - Has definido:

        ```python
        app = Flask("quoteapi")
        ```

        cuando definimos la app de Flask, lo hacemos con "__name__". Lo que hace es llamarse a sí mismo; es algo interno de python, no es un "format" como tal. Te dejo este artículo que lo explica: [https://blog.miguelgrinberg.com/post/why-do-we-pass-name-to-the-flask-class](https://blog.miguelgrinberg.com/post/why-do-we-pass-name-to-the-flask-class)

    - Por lo demás está todo bien: código sintético donde llamas a otras funciones que hacen otras cosas. Quizá pueda haber algo de duplicidad en las funciones que decía antes que se pueda refactorizar con parametrización y con quizá eliminar alguna función.
    - Muy top que hayas escrapeado los datos. Has hecho un proyecto integrando un montón de tecnologías y de técnicas: has cogido datos, los has limpiado, los has metido en un base de datos y has sacado conclusiones (en este caso de sentiment). Es todo el pipeline de un data analyst y lo has clavado.

    Enhorabuena Ana por lo que te pongo arriba. A este proyecto siempre se le pueden añadir más cosas:  hacer más visualización, meter más datos, puedes deployearlo (para eso necesitas pasar la base de datos de Mongo Compass a Mongo Atlas), pero el proyecto está genial. En unas semanas habéis conseguido nutrir una base de datos a través de una aplicación vuestra y habeís sacado insights. Y esto es sólo el principio, esto lo puedes escalar de muchas formas. 

    A tope Ana!! 💪 🚀

    ![image](https://user-images.githubusercontent.com/54676992/108981112-b0e18200-768c-11eb-9525-e1166f10739b.png)
