### ISSUE TITLE
[api-sentiment-project] Sergio Calero

### ISSUE THREAD

**Issue by SergioCaler0** [Ironhack-Data-Madrid-Enero-2021/W6-api-sentiment-project#14]

**Comment by olmocorell** [comment]
¡¡Hola Hola Maifreeeeeeeeeeeeeeeeeeeeen!! 🚀 💪🏻 🔝 
En primer lugar, perdona por la tardanza a la hora de corregir esto.


### Readme
Está genial y está súper cómo has metido los ejemplos de cómo hacer llamadas a tu API. Lo único que me falta aquí es un apartado de stack de tecnologías utilizadas con enlaces a documentación.
![Captura de pantalla 2021-03-09 a las 11 32 56](https://user-images.githubusercontent.com/57899051/110458559-307b4200-80cc-11eb-9130-abb6ca0413ed.png)


### Code/Repository structure
La estructura del repositorio está genial, está perfect, al final habéis seguido la estructura de archivos de clase y está bien. Así que muy bien.
Está super que las funciones de los endpoints sean pequeñitas y dentro tengas llamadas a otras funciones que tienes fuera

![Captura de pantalla 2021-03-09 a las 13 16 57](https://user-images.githubusercontent.com/57899051/110469273-bb166e00-80d9-11eb-963f-aaf91ce95303.png)

Aquí:
![Captura de pantalla 2021-03-09 a las 16 54 28](https://user-images.githubusercontent.com/57899051/110499004-1fe0c100-80f8-11eb-8a05-94897851d07e.png)
Echo de menos que hagas funciones de check antes de introducir datos en la base de datos

### Code efficiency / Code syntax (conventions)
La sintaxis de las funciones está perfecta y el código en general es eficiente. Además están bien documentadas
¡Enhorabuena!

### Improvements
- doc en el readme stack de tecnologías
- funciones de check y un poco de programación defensiva


¡¡En general muy buen trabajo Sergio!!
Que se acaba el bootcaaaaaaaaaaaaaaaaaaaaaaaaaamp


![unnamed](https://user-images.githubusercontent.com/57899051/110499697-c927b700-80f8-11eb-9e62-1bbb5d327561.png)
