### ISSUE TITLE
[W6-api-sentiment-project] Carlota Portillo

### ISSUE THREAD

**Issue by xarlomi** [Ironhack-Data-Madrid-Enero-2021/W6-api-sentiment-project#15]
https://github.com/xarlomi/Friends-API-creation

**Comment by olmocorell** [comment]
¡¡Hola Hola Carlotaaaaaaaaaaaaaaa!! 🚀 💪🏻 
Aquí estoy para contarte cositas sobre el proyecto. 


### Readme
Está y está bien, pero...¿qué podemos añadirle?
Un apartado de stack de tecnologías con enlaces tipo así:
![Captura de pantalla 2021-03-03 a las 7 17 32](https://user-images.githubusercontent.com/57899051/109761785-8776a800-7bf0-11eb-871d-8f4d9baf2318.png)
Y luego, es cierto que me pones los endpoints, pero ¿cómo tengo que organizar los datos para ponerlos en tu api si quisiera llamarla?
Yo habría puesto algún ejemplo de código de cómo usar los endpoints tipo documentación:
<img width="873" alt="Captura de pantalla 2021-02-26 a las 10 27 35" src="https://user-images.githubusercontent.com/57899051/109281981-3f850900-781d-11eb-9859-2a48314741eb.png">
Viendo esto, seguro que se puede mejorar, pero así es como lo puse yo en el readme, un ejemplo de cómo había que tener los datos estructurados para hacer las request a la API.


### Code/Repository structure
Vamos a la estructura del repo.
Por aquí hay cosas mejorables...
![Captura de pantalla 2021-03-03 a las 7 20 47](https://user-images.githubusercontent.com/57899051/109763228-133d0400-7bf2-11eb-8687-40201f29b49c.png)

Todo esto está dentro de la carpeta starter code. Debería haber una carpeta de data con los .csv
Por otra parte, los jupyter notebooks los ponemos a parte, o bien en una carpeta de notebooks o fuera, a la altura del readme, si vamos a utilizar el jupyter como demostración de las llamadas a una API lo dejamos fuera, pero si estamos haciendo data cleaning o así, lo metemos en una carpeta de notebooks.

### Code efficiency / Code syntax (conventions)
En cuanto a esto, decirte que habría molado que, como mejora, hicieras un endpoint con el sentiment analisys, que un endpoint devolviera directamente el sentimiento de las frases, o los grupos o así.

Está realmente bien que tengas unas funciones check en un archivo aparte check.py. enhorabuena.
![Captura de pantalla 2021-03-03 a las 7 34 29](https://user-images.githubusercontent.com/57899051/109763788-e5a48a80-7bf2-11eb-980c-4317f7cc67db.png)

Está realmente bien que tengas estas funciones sencillas dentro de los endpoint
![Captura de pantalla 2021-03-03 a las 7 36 01](https://user-images.githubusercontent.com/57899051/109763902-1c7aa080-7bf3-11eb-8061-d494ad84ac4f.png)

Y [aquí](https://github.com/xarlomi/Friends-API-creation/blob/main/starter-code/api_tests.ipynb), en el jupyter donde pruebas la api, bastaba con importar la librería requests, porque la idea es que si tenemos la api funcionando y corriendo en nuestro servidor local, podemos hacer llamadas desde jupyter solamente con la url en local y el módulo requests.

### Improvements
Has hecho muy buen trabajo Carlota, hay mucho código muy bien picado pero te falta un poco de organización general y quizás entender algún concepto, y me refiero por el tema del jupyter de llamadas a la api.

- Readme (stack de tecnologías con enlaces y ejemplos de ejecución)
- Organización del repo, carpetas y archivos
- Sentiment en un endpoint

La estructura general del código está bien, imagino que al final con los repasos de flask, ha quedado medio claro.
¡¡Buen trabajooooooooooo!!

![6b2d5980bce5a2d7024e95afabf21988](https://user-images.githubusercontent.com/57899051/109764699-2b158780-7bf4-11eb-81fb-1a3736729e0b.png)
