### ISSUE TITLE
[API-Sentiment-Project]Santiago

### ISSUE THREAD

**Issue by santhart97** [Ironhack-Data-Madrid-Enero-2021/W6-api-sentiment-project#16]
https://github.com/santhart97/PROJECT-4

**Comment by breogann** [comment]
Hola Santi! 🙋🏻‍♂️

Te coy contando:

- Respecto a la **organización del repositorio 📚**
    - El .gitignore: tienes archivos ocultos/temporales que no se te han ignorado. Tienes: .ipynb_checkpoints, .vscore, pycache y una carpeta con la info del entorno. Tienes que borrarlos del caché de git

        ```python
        git rm --cached .vscode
        ```

        luego tendrás que asegurarte de que están incluidos en el .gitignore y volver a hacer el commit. 

    - Tienes un jupyter sin título.
- El **[README.md](http://readme.md) ✍🏻**:
    - No tienes readme Santiago...
- El **código 👩‍💻:**
    - El jupyter sin título lo tienes con errores
    - La parte de mongoconnection, lo que tienes, está bien
    - Cuando crees las funciones, asegúrate de poner docstrings
    - El planteamiento de [app.py](http://app.py) también está bien
    - Has definido:

        ```python
        app = Flask("lotr_quotes")
        ```

        cuando definimos la app de Flask, lo hacemos con "__name__". Lo que hace es llamarse a sí mismo; es algo interno de python, no es un "format" como tal. Te dejo este artículo que lo explica: [https://blog.miguelgrinberg.com/post/why-do-we-pass-name-to-the-flask-class](https://blog.miguelgrinberg.com/post/why-do-we-pass-name-to-the-flask-class)

    Santi, la organización del repositorio es un poco caótica. Tienes archivos sin ignorar, jupyters sin título y con errores y tienes muy pocas funciones. El sentiment analysis está bien, pero asegúrate de que la gráfica sea interpretable. Tienes lo mínimo: app.py, mongoconnection y checking.py, pero me faltan muchas funciones y una mejor organización. Por supuesto también el readme. 

    Tendrás que darle una vuelta a este proycto, porque está muy mejorable...

    ![image](https://user-images.githubusercontent.com/54676992/108981112-b0e18200-768c-11eb-9525-e1166f10739b.png)
