### ISSUE TITLE
[W6-api-sentiment-project] Ángela Navarrro

### ISSUE THREAD

**Issue by angelanavarrog** [Ironhack-Data-Madrid-Enero-2021/W6-api-sentiment-project#2]

**Comment by angelanavarrog** [comment]
https://github.com/angelanavarrog/API_project

**Comment by breogann** [comment]
Hola Ángela! 🙋🏻‍♂️

Te coy contando:

- Respecto a la **organización del repositorio 📚**
    - El .gitignore: No se te ha colado ningún archivo oculto/temporal, o sea que perfecto. Veo por el último commit que se te coló pero que lo borraste 👏
    - El [README.md](http://readme.md) por convención se pone siempre con el nombre en mayúscula y la extensión en minúscula. De hecho habría jurado que si no está puesto así, github no lo renderiza, pero se ve que sí que lo hace 🤷‍♂️. En cualquier caso, pls, por el TOC de todos.
    - Por lo demás, yo lo organizaría como: files/ → **data/**, Code/ → **src/** y los jupyters aparte.
    - También, el archivo principal que es el que empieza la cascada y desencadena todo suele ir a nivel de root. ¿Por qué? porque cuando te clonas un repositorio o te descargas un programa, el archivo ejecutable debe encontrarse fácilmente y tener un nombre relativamente genérico: main.py, app.py, [api.py](http://api.py) (en este caso). Claro que si lo mueves de sitio, recuerda cambiar también las rutas relativas de las importaciones!
- El **[README.md](http://readme.md/) ✍🏻**:
    - Súuper bien explicado. Has incluido las tecnologías, enlaces, etc.
    - Súper importante: pon ejemplos de endpoints, como siempre, que alguien que no sepa de código sea capaz de entender lo que habéis hecho.
    - Puedes poner también alguna gráfica cuando hagas el sentiment analysis.
    - El sentiment analysis, cuando lo hagas, acuérdate de meterlo bajo un endpoint!
- El **código 👩‍💻:**
    - En general: súper bien por poner los docstrings. Asegúrate de que tienen tres partes: descripción, argumentos y return. Ayúdate también de hashtags para comentar otras cosas si crees que te puede añadir valor: la propia estructura del [archivo.py](http://archivo.py), por ejemplo.
    - También súper buena modularización de las funciones: en [api](http://apiu.py).py las funciones mínimas con los decoradores que llamen a funciones definidas en otros sitios, como helpers 👏
    - Respecto a la parametrización:

        ```python
        @app.route("/users/complete")
        def users():
            '''
            Endpoint to test the data in the API
            Returns: existing users in our database
            '''
            return json_util.dumps(list_users())

        @app.route("/groups/complete")
        def groups():
            '''
            Endpoint to test the data in the API
            Returns: existing groups in our database
            '''
            return json_util.dumps(list_groups())
        ```

        si las dos funciones lo que hacen es comprobar/traer cosas y depende de la colección de donde se vienen, puedes parametrizar la función para que en función de argumento haga una cosa o haga otra. Al final tener funciones muy parecidas puede ser señal de que hace falta refactorizar.

    - Como decíamos ayer, puedes incluir el sentiment analysis dentro de un endpoint. Es cuestión de modularizar las funciones y poner un decorador más. Puedes incluso hacer que, en función de lo que pidas, devuelvas una gráfica. También puedes hacerlo por grupos, por usuarios, por usuarios en el tiempo (antes o después de un evento), por palabras más usadas, etc.

    Enhorabuena Ángela! Has creado una base de datos, has creado enpdpoints de post, de get y no te queda casi nada para hacer sentiment analysis. A este proyecto siempre se le pueden añadir más cosas:  hacer más visualización, meter más datos, puedes deployearlo (para eso necesitas pasar la base de datos de Mongo Compass a Mongo Atlas), pero el proyecto está genial. En unas semanas habéis conseguido nutrir una base de datos a través de una aplicación vuestra y habéis sacado insights. Y esto es sólo el principio, esto lo puedes escalar de muchas formas. 

    Y si lo quieres retocar, igual te puedes meter con SQL y tener un pedazo de portfolio.

    A tope Ángela!! 💪 🚀

    ![https://user-images.githubusercontent.com/54676992/108981112-b0e18200-768c-11eb-9525-e1166f10739b.png](https://user-images.githubusercontent.com/54676992/108981112-b0e18200-768c-11eb-9525-e1166f10739b.png)
