### ISSUE TITLE
[W6-api-sentiment-project] Antonio García

### ISSUE THREAD

**Issue by antoniogarciagiron** [Ironhack-Data-Madrid-Enero-2021/W6-api-sentiment-project#3]
https://github.com/antoniogarciagiron/API-Toni-Project.git

**Comment by olmocorell** [comment]
¡¡Toniiiiiiii!! 🚀 🚀 
Te cuento cosinas del proyecto:

### Readme

Está muy muy bien. 
¿Qué añadiría yo?
- Unos enlaces a la documentación en esta parte:
<img width="362" alt="Captura de pantalla 2021-02-26 a las 10 25 55" src="https://user-images.githubusercontent.com/57899051/109281777-03ea3f00-781d-11eb-94b8-801dc97969f2.png">
Igual que has hecho con RottenTomatoes.
Por otra parte:
Yo habría puesto algún ejemplo de código de cómo usar los endpoints tipo documentación:
<img width="873" alt="Captura de pantalla 2021-02-26 a las 10 27 35" src="https://user-images.githubusercontent.com/57899051/109281981-3f850900-781d-11eb-9859-2a48314741eb.png">
Viendo esto, seguro que se puede mejorar, pero así es como lo puse yo en el readme, un ejemplo de cómo había que tener los datos estructurados para hacer las request a la API.


### Code/Repository structure
En cuanto a la estructura del repositorio y los archivos:
<img width="807" alt="Captura de pantalla 2021-02-26 a las 10 38 37" src="https://user-images.githubusercontent.com/57899051/109283207-c981a180-781e-11eb-8a53-018fc4e824a1.png">
Yo dejaría el jupyter fuera de la carpeta del código de la API, y, si solo hay uno y es como una presentación, lo dejaría a la altura del readme, con un título llamativo, porque en ese jupyter vamos a ver que realmente funciona tu api y cómo lo hace.
Y tanto el csv como el json los metería en una carpeta fuera de la API de data.

### Code efficiency / Code syntax (conventions)
En primer lugar, enhorabuena por tener documentadas todas las funciones.
En cuanto a esto: 
<img width="977" alt="Captura de pantalla 2021-02-26 a las 11 15 46" src="https://user-images.githubusercontent.com/57899051/109287535-fb493700-7823-11eb-9eac-a346bcfa81e3.png">
Este código podemos atomizarlo, aquí hay código que se puede incluir en funciones en tu archivo de check.

Por lo demás, está muy bien. Haces lo que se te pide y el código es bastante eficiente en general.
Ahora que tienes la base, puedes animarte con más endpoints que llamen a funciones más complejas ... esas funciones pueden devolver gráficos, NLP, o incluso (ya lo investigarás más adelante) renderizar plantillas html.

### Improvements
Te pongo por aquí un pequeño resumen de lo que te he ido contando arriba:
- Enlaces a doc en el readme
- Ejemplos de ejecución del código en el readme
- Atomización de endpoints / funciones check
- Organización del repo (jupyter, csv, json)

¡Muy buen trabajo Toni! Estás trabajando muy duro y estoy viendo una evolución súper positiva en tu aprendizaje. ¡¡Enhorabuena!!

![6b2d5980bce5a2d7024e95afabf21988](https://user-images.githubusercontent.com/57899051/109289117-0735f880-7826-11eb-8442-03277278c7ff.png)
