### ISSUE TITLE
[W6-api-sentiment-project] Floren Gutiérrez

### ISSUE THREAD

**Issue by florengutierrez** [Ironhack-Data-Madrid-Enero-2021/W6-api-sentiment-project#4]
https://github.com/florengutierrez/Api-sentiment-project

**Comment by florengutierrez** [comment]
Ras! falta completar Readme! y buscar porqué me han dejado de tirar el post! durante la semana seguiré dandole caña!

**Comment by olmocorell** [comment]
¡¡Hola Hola Floreeeeeeeeeeeeeeeeeeen!! 🚀 🚀 🚀  
Te cuento unas cosinas

### Readme
Vale, ya me has dicho que tienes que completarlo. ¡No lo dejes porfi! 
Ideas para cuando lo hagas:
- Stack de tecnologías con enlaces tipo así
![Captura de pantalla 2021-03-03 a las 7 46 16](https://user-images.githubusercontent.com/57899051/109764997-89db0100-7bf4-11eb-8dac-370270ac2d75.png)
- Ejemplos de llamadas a la api
Algún ejemplo de código de cómo usar los endpoints tipo documentación:
<img width="873" alt="Captura de pantalla 2021-02-26 a las 10 27 35" src="https://user-images.githubusercontent.com/57899051/109281981-3f850900-781d-11eb-9859-2a48314741eb.png">
Viendo esto, seguro que se puede mejorar, pero así es como lo puse yo en el readme, un ejemplo de cómo había que tener los datos estructurados para hacer las request a la API.

### Code/Repository structure
Esto está de 10. ¡¡¡Enhorabuena!!! 🏅 

### Code efficiency / Code syntax (conventions)
Está genial que tengas estas funciones tan pequeñitas que llaman a otras funciones que están fuera.
![Captura de pantalla 2021-03-03 a las 7 48 24](https://user-images.githubusercontent.com/57899051/109765213-d6bed780-7bf4-11eb-8151-7de78f748200.png)
También están genial tus funciones de check.
[Aquí](https://github.com/florengutierrez/Api-sentiment-project/blob/main/api.tests.ipynb), en el jupyter donde pruebas la api, bastaba con importar la librería requests, porque la idea es que si tenemos la api funcionando y corriendo en nuestro servidor local, podemos hacer llamadas desde jupyter solamente con la url en local y el módulo requests.

Entiendo que al final, con los repasos de flask, ha quedado medio claro cómo se hace. El código que has escrito está bien. Revisa por qué no te funciona lo que te falla y si quieres en algún momento lo vemos tranquilamente.

### Improvements
- Terminar el readme
- Hacer algún endpoint más
- Importar solo requests en el jupyter de testing de la api
- Meter un endpoint con sentiment analysis


¡¡Buen trabajo Floreeeeeeeeeeeen!!

![6b2d5980bce5a2d7024e95afabf21988](https://user-images.githubusercontent.com/57899051/109765832-a7f53100-7bf5-11eb-9750-4f12774db00a.png)
