### ISSUE TITLE
[W6-api-sentiment-project] Alfredo Zavala

### ISSUE THREAD

**Issue by alfredozavala14** [Ironhack-Data-Madrid-Enero-2021/W6-api-sentiment-project#5]
https://github.com/alfredozavala14/api-sentiment-project.git

**Comment by olmocorell** [comment]
¡¡Hola Hola Alfredooooooooooo 🚀 💪🏻 🚀 💪🏻 !! 
En primerito lugar, perdona por haber tardado tanto en venir a corregir este proyecto.
Te cuento cosinas:

### Readme
Está genial, pero te cuento, no te carga la imagen, échale un ojo:
![Captura de pantalla 2021-03-09 a las 18 03 37](https://user-images.githubusercontent.com/57899051/110508871-c8dfe980-8101-11eb-8c24-5d008ce8cb45.png)
Por otra parte, donde explicas los endpoints:
Habría puesto algún ejemplo de código de cómo usar los endpoints tipo documentación:
<img width="873" alt="Captura de pantalla 2021-02-26 a las 10 27 35" src="https://user-images.githubusercontent.com/57899051/109281981-3f850900-781d-11eb-9859-2a48314741eb.png">
Viendo esto, seguro que se puede mejorar, pero así es como lo puse yo en el readme, un ejemplo de cómo había que tener los datos estructurados para hacer las request a la API.


### Code/Repository structure
Aquí: 
![Captura de pantalla 2021-03-09 a las 18 06 16](https://user-images.githubusercontent.com/57899051/110509201-25430900-8102-11eb-9bc1-05cb9cc03748.png)
Está guay, pero yo habría dejado fuera el api.py si realmente luego todo lo demás de la api está en helpers.
El resto está genial

### Code efficiency / Code syntax (conventions)
Está súper bien que hayas hecho funciones pequeñitas dentro de los endpoints
![Captura de pantalla 2021-03-09 a las 18 07 01](https://user-images.githubusercontent.com/57899051/110509301-40157d80-8102-11eb-9ed3-9605e5457699.png)


Aunque te diré que creo que esta función puedes parametrizarla y atomizarla en funciones más pequeñas que hagan cosas más concretas:
![Captura de pantalla 2021-03-09 a las 18 08 22](https://user-images.githubusercontent.com/57899051/110509495-72bf7600-8102-11eb-8cf4-eb92c0f1700d.png)

El resto está genial, el código está muy bien estructurado, los endpoints hacen pequeñas funciones que llaman a otras. Por lo general entiendes como funciona una API y has hecho un montón de endpoints.
Muy buen trabajo Alfredo, es un gran proyecto.


### Improvements
- Organización repo api.py
- Readme
- Atomización funciones parametrizadas que hagan cosas más concretas
¡¡¡Vamos que esto se acabaaaaaaaaa!!!


![6b2d5980bce5a2d7024e95afabf21988](https://user-images.githubusercontent.com/57899051/110511590-a8655e80-8104-11eb-85f4-b29d404cbd59.png)
