### ISSUE TITLE
[W6-api-sentiment-project] Alex Moreno

### ISSUE THREAD

**Issue by amorenorp** [Ironhack-Data-Madrid-Enero-2021/W6-api-sentiment-project#7]
jejeje hice el gitignore y no lo guardé así que se subieron cosas que no quería.   😺

**Comment by amorenorp** [comment]
https://github.com/amorenorp/api-sentiment-project


se me olvidó poner el enlace jajaja

**Comment by breogann** [comment]
Hola Álex! 🙋🏻‍♂️

Te coy contando:

- Respecto a la **organización del repositorio 📚**
    - El .gitignore: se te han colado archivos ocultos/temporales (como me comentas). Aunque los borres, git ya los ha trackeado, así que tienes que borrarlos del caché:

        ```bash
        git rm --cached .vscode
        ```

        una vez añadido, es cuestión de añadirlo al gitignore y volver a comitear. Lo mismo con .DS_Store.

    - Para las carpetas, la estructura que te propondría es: data (en vez de csv), img, src (para source) y los archivos de mongoConnection dentro de src. Al final son convenciones que puedes o no seguir, pero se suelen estructurar de esa forma. En cualquier caso está bien.
- El **[README.md](http://readme.md/) ✍🏻**:
    - Súuper bien explicado. Has incluido las tecnologías, enlaces, y qué hace cada archivo.
    - Asegúrate de incluir también ejemplos de los endpoints! Soy muy pesado, pero haced la documentación como os gustaría encontrarla. Siempre pon ejemplos de uso.
    - Puedes poner también alguna gráfica cuando hagas el sentiment analysis.
    - Aprovecha que has utilizado HTML para añadir alguna captura! Está bien que utilices HTML, pero no le dediques mucho tiempo, siempre prioriza por python y por visualización (pero vamos, que genial que lo explores 🙂)
- El **código 👩‍💻:**
    - Has definido:

        ```python
        app = Flask("shout_park")
        ```

        cuando definimos la app de Flask, lo hacemos con "__name__". Lo que hace es llamarse a sí mismo; es algo interno de python, no es un "format" como tal. Te dejo este artículo que lo explica: [https://blog.miguelgrinberg.com/post/why-do-we-pass-name-to-the-flask-class](https://blog.miguelgrinberg.com/post/why-do-we-pass-name-to-the-flask-class)

    - Genial el uso de los docstrings.
    - También súper buena modularización de las funciones: en [api](http://apiu.py).py las funciones mínimas con los decoradores que llamen a funciones definidas en otros sitios, como source 👏
    - Como decíamos ayer, puedes incluir el sentiment analysis dentro de un endpoint. Es cuestión de modularizar las funciones y poner un decorador más. Puedes incluso hacer que, en función de lo que pidas, devuelvas una gráfica. También puedes hacerlo por grupos, por usuarios, por usuarios en el tiempo (antes o después de un evento), por palabras más usadas, etc.

    Enhorabuena Álex! Has creado una base de datos, has creado enpdpoints de post, de get y has hecho sentiment analysis. A este proyecto siempre se le pueden añadir más cosas:  hacer más visualización, meter más datos, puedes deployearlo (para eso necesitas pasar la base de datos de Mongo Compass a Mongo Atlas), pero el proyecto está genial. En unas semanas habéis conseguido nutrir una base de datos a través de una aplicación vuestra y habéis sacado insights. Y esto es sólo el principio, esto lo puedes escalar de muchas formas. 

    A tope Álex!! 💪 🚀

    ![https://user-images.githubusercontent.com/54676992/108981112-b0e18200-768c-11eb-9525-e1166f10739b.png](https://user-images.githubusercontent.com/54676992/108981112-b0e18200-768c-11eb-9525-e1166f10739b.png)
