### ISSUE TITLE
[W6-api-sentiment-project] JJ Triviño

### ISSUE THREAD

**Issue by JJTrivino** [Ironhack-Data-Madrid-Enero-2021/W6-api-sentiment-project#8]
https://github.com/JJTrivino/Family-Sentiment

**Comment by olmocorell** [comment]
¡¡Hola Juanjooooooooo!! 🚀 💪🏻 🚀 💪🏻 
En primer lugar, perdona por haber tardado tanto en corregir este proyecto
Te cuento cosas del proyecto

### Readme
Está bastante bien, pero, un par de cosas que metería:
- Stack de tecnologías con enlaces tipo así
![Captura de pantalla 2021-03-03 a las 7 46 16](https://user-images.githubusercontent.com/57899051/109764997-89db0100-7bf4-11eb-8dac-370270ac2d75.png)
- Ejemplos de llamadas a la api
Algún ejemplo de código de cómo usar los endpoints tipo documentación:
<img width="873" alt="Captura de pantalla 2021-02-26 a las 10 27 35" src="https://user-images.githubusercontent.com/57899051/109281981-3f850900-781d-11eb-9859-2a48314741eb.png">
Viendo esto, seguro que se puede mejorar, pero así es como lo puse yo en el readme, un ejemplo de cómo había que tener los datos estructurados para hacer las request a la API.



### Code/Repository structure
Aquí en el repo tienes un poco de caos:
![Captura de pantalla 2021-03-09 a las 17 03 17](https://user-images.githubusercontent.com/57899051/110500296-5965fc00-80f9-11eb-8b98-eebdc00bcf43.png)
Esto es, hay un csv que debería estar en la carpeta de data...luego el checking.py, mongoconection.py ... todo esto debería estar dentro de la carpeta SRC.

[Aquí](https://github.com/JJTrivino/Family-Sentiment/blob/main/tests.ipynb), en este jupyter, para hacer las request a nuestra api bastaba con importar la librería requests, porque la idea es que si tenemos la api funcionando y corriendo en nuestro servidor local, podemos hacer llamadas desde jupyter solamente con la url en local y el módulo requests.
![Captura de pantalla 2021-03-09 a las 17 26 30](https://user-images.githubusercontent.com/57899051/110503543-97b0ea80-80fc-11eb-8b26-a4c03cbcbfe9.png)

[Esto](https://github.com/JJTrivino/Family-Sentiment/blob/main/sentimentalism.ipynb) sería ideal que lo hubieras hecho un endpoint, ahora que ya controlas un poco más de código, plantéatelo como reto para mejorar tu api cuando acabes el bootcamp. O si quieres hacer una nueva, ya tienes ideas 😄 

### Code efficiency / Code syntax (conventions)
Haces bien en tener funciones pequeñitas dentro de los endpoints y llamar a otras funciones que tienes fuera, como pueden ser funciones de check.
![Captura de pantalla 2021-03-09 a las 17 47 24](https://user-images.githubusercontent.com/57899051/110506586-83222180-80ff-11eb-95bd-3e3e1a498e27.png)
Es verdad que podrías haber hecho más endpoints, pero te lo dejo también como reto para las próximas.

En cuanto a la estructura y eficiencia del código, es muy similar a lo visto en clase, así que está correcto.


### Improvements
- Readme
- Endpoints
- Sentiment dentro de endpoint
- Organización del repo

En general buen trabajo, espero que hayas entendido finalmente como funciona flask y como podemos montar una API facilita con conexión a Mongo.

¡¡¡Seguimooooos!!! ¡¡Esto se acaba!!


![6b2d5980bce5a2d7024e95afabf21988](https://user-images.githubusercontent.com/57899051/110508406-42c3a300-8101-11eb-8a54-3941989500a5.png)
