### ISSUE TITLE
[W6-api-sentiment-project] Ana de Luna

### ISSUE THREAD

**Issue by AnadeLuna** [Ironhack-Data-Madrid-Enero-2021/W6-api-sentiment-project#9]
https://github.com/AnadeLuna/Proyect-Api

**Comment by breogann** [comment]
Hola Ana! 🙋🏻‍♂️

Te coy contando:

- Respecto a la **organización del repositorio 📚**
    - El .gitignore: No se te ha colado ningún archivo oculto/temporal, osea que perfecto.
    - En data tienes las imágenes, eso lo puedes poner en una carpeta concreta de imgs. Data como tal no tienes porque lo tienes todo en mongodb. Si hubieras utilizado un csv para nutrir la base de datos, entonces sí tendrías data para esa carpeta. Pero si no, la puedes eliminar.
    - Para el jupyter de mongo, como te decíamos, sólo hace falta que importes requests. Al final el jupyter lo único que va a hacer es colocar la dirección en la barra de navegación de igual forma que lo harías tú. Y esa dirección lo que hace es llamar a la función del [api.py](http://api.py) que tiene debajo, que a su vez llama a la de mongo connection etc. Pero ese jupyter no hace conexión con la base de datos, sino que llama a la primera función que desencadena el resto.
- El **[README.md](http://readme.md/) ✍🏻**:
    - Súuper bien explicado. Has incluido las tecnologías, enlaces, etc.
    - También has puesto ejemplos de los endpoints
    - Puedes poner también alguna gráfica.
    - Nada que decir, como siempre, que alguien que no sepa de código sea capaz de entender lo que habéis hecho.
- El **código 👩‍💻:**
    - En general: No has hecho los docstrings. Acostúmbrate a poner docstring diciendo qué hace cada función y qué recibe y qué devuelve; sobre todo por hacerte un favor a tu yo del futuro. Los hashtags no aparecen si haces un:

        ```python
        #Este comentario no saldría
        def suma(a+b)
        '''Recibe dos numeros
        Devuelve: la suma'''
        	return a+b

        #al hacer esto:
        suma.__doc__
        ```

    - También súper buena modularización de las funciones: en [api](http://apiu.py).py las funciones mínimas con los decoradores que llamen a funciones definidas en otros sitios, como mongoconnection 👏
    - Respecto a la parametrización:

        ```python
        def delete_user(name,age,sex,lookingfor):
            dic = {"Name":f"{name}",
              "Age":f"{age}",
              "Sex":f"{sex}",
              "Looking for":f"{lookingfor}"}
            return users.remove(dic)

        #Funtion to delete a message.
        def delete_message(name,messa,match):
            dic_mes = {"Name":f"{name}",
              "Message":f"{messa}",
              "Match":f"{match}"}
            return message.remove(dic_mes)
        ```

        si las dos funciones lo que hacen es eliminar cosas y depende de la colección de donde se eliminen, puedes parametrizar la función para que en función de alrgumento haga una cosa o haga otra. Al final tener funciones muy parecidas puede ser señal de que hace falta refactorizar.

    - Como decíamos ayer, puedes incluir el sentiment analysis dentro de un endpoint. Es cuestión de modularizar las funciones y poner un decorador más. Puedes incluso hacer que, en función de lo que pidas, devuelvas una gráfica. También puedes hacerlo por grupos, por usuarios, por usuarios en el tiempo (antes o después de un evento), por palabras más usadas, etc.

    Enhorabuena Ana! Has creado una base de datos, has creado enpdpoints de post, de get y has hecho un sentiment analysis.  A este proyecto siempre se le pueden añadir más cosas:  hacer más visualización, meter más datos, puedes deployearlo (para eso necesitas pasar la base de datos de Mongo Compass a Mongo Atlas), pero el proyecto está genial. En unas semanas habéis conseguido nutrir una base de datos a través de una aplicación vuestra y habéis sacado insights. Y esto es sólo el principio, esto lo puedes escalar de muchas formas. 

    A tope Ana!! 💪 🚀

    ![https://user-images.githubusercontent.com/54676992/108981112-b0e18200-768c-11eb-9525-e1166f10739b.png](https://user-images.githubusercontent.com/54676992/108981112-b0e18200-768c-11eb-9525-e1166f10739b.png)
